---
- name: Install commons dependencies
  apt:  
    update_cache: yes
    name:
      - tree
      - curl
      - htop
      - wget
      - vim
      - git
      - zip
      - unzip
    state: present
