---

- name: Update apt package manager repositories cache
  apt: update_cache=yes

- name: Upgrade installed packages
  apt: upgrade=dist

- name: Install commons dependencies
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - tree
    - curl
    - htop
    - wget
    - vim
    - git
    - zip