---

- name: Update apt package manager repositories cache
  apt: update_cache=yes

- name: Upgrade installed packages
  apt: upgrade=dist

- name: Install commons dependencies
  apt:  
    name:
      - tree
      - curl
      - htop
      - wget
      - vim
      - git
      - zip
      - unzip
  state: present
