---

- name: Update apt package manager repositories cache
  apt: update_cache=yes

- name: Upgrade installed packages
  apt: upgrade=dist

- name: Install commons dependencies
  apt: name=[u'tree', u'curl', u'htop', u'wget', u'vim', u'git', u'zip', u'unzip'] state=present update_cache=yes
