---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install commons dependencies
  apt: update_cache=yes name={{item}} state=latest
  with_items:
    - tree
    - curl
    - htop
    - wget
    - vim
    - git
