---
- name: Update apt package manager repositories cache
  apt: update_cache=yes

- name: Install commons dependencies
  apt: name={{item}} state=present
  with_items:
    - tree
    - curl
    - htop
    - wget
    - vim
    - git
    - zip
    - unzip
