---
- name: Install commons dependencies
  become: true
  apt: update_cache=yes


- name: Install commons dependencies
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - curl
    - htop
    - wget
    - vim
    - git
    - tree
