---
- name: Install commons dependencies
  apt: name={{item}} state=present  update_cache=yes 
  become: true
  become_method: sudo
  with_items:
    - tree
    - curl
    - htop
    - wget
    - vim
    - git
    - ansible
    - zip
    - unzip
