---
- name: Update yum package manager repositories cache
  yum: update_cache=yes

- name: Install commons dependencies
  yum: name={{item}} state=present
  with_items:
    - tree
    - curl
    - htop
    - wget
    - vim
    - git
    - zip
    - unzip
