---
  
- name: Install Docker
  apt: name=docker.io

- name: Creater Docker group
  group: name=docker state=present

- name: Add current user to Docker group
  user: name="usermod" groups=docker append=yes
