---
- name: Install Docker
  apt: update_cache=yes name=docker.io state=present 

- name: Creater Docker group
  group: name=docker state=present

- name: Add current user to Docker group
  user: name="usermod" groups=docker append=yes
